// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmScenario.proto

package ca.wise.fire.proto;

public final class CwfgmScenarioOuterClass {
  private CwfgmScenarioOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_Threshold_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_Threshold_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_FmcOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_FmcOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_FwiOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_FwiOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_FbpOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_FbpOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_FgmOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_FgmOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_ScenarioFuelPercentile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_ScenarioFuelPercentile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_Components_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_Components_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_Reference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_Reference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_TargetReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_TargetReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_FilterOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_FilterOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_AssetOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_AssetOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_WeatherIndexOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_WeatherIndexOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmScenario_IdwExponent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmScenario_IdwExponent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023cwfgmScenario.proto\022\024WISE.FireEnginePr" +
      "oto\032\nmath.proto\032\013wtime.proto\032\036google/pro" +
      "tobuf/wrappers.proto\032\021cwfgmFilter.proto\"" +
      "\341,\n\rCwfgmScenario\022\017\n\007version\030\001 \001(\005\022#\n\tst" +
      "artTime\030\002 \001(\0132\020.HSS.Times.WTime\022!\n\007endTi" +
      "me\030\003 \001(\0132\020.HSS.Times.WTime\022-\n\017displayInt" +
      "erval\030\004 \001(\0132\024.HSS.Times.WTimeSpan\022B\n\nfbp" +
      "Options\030\005 \001(\0132..WISE.FireEngineProto.Cwf" +
      "gmScenario.FbpOptions\022B\n\nfgmOptions\030\006 \001(" +
      "\0132..WISE.FireEngineProto.CwfgmScenario.F" +
      "gmOptions\022B\n\nfmcOptions\030\007 \001(\0132..WISE.Fir" +
      "eEngineProto.CwfgmScenario.FmcOptions\022B\n" +
      "\nfwiOptions\030\010 \001(\0132..WISE.FireEngineProto" +
      ".CwfgmScenario.FwiOptions\022O\n\013percentiles" +
      "\030\013 \003(\0132:.WISE.FireEngineProto.CwfgmScena" +
      "rio.ScenarioFuelPercentile\022R\n\013stopOption" +
      "s\030\014 \001(\01328.WISE.FireEngineProto.CwfgmScen" +
      "ario.StopModellingOptionsH\001\210\001\001\022\021\n\004name\030\r" +
      " \001(\tH\002\210\001\001\022\025\n\010copyName\030\016 \001(\tH\003\210\001\001\022\025\n\010comm" +
      "ents\030\017 \001(\tH\004\210\001\001\022=\n\022temporalConditions\030\020 " +
      "\001(\0132!.WISE.GridProto.TemporalCondition\022G" +
      "\n\ncomponents\030\021 \001(\0132..WISE.FireEngineProt" +
      "o.CwfgmScenario.ComponentsH\005\210\001\001\022<\n\003idw\030\022" +
      " \001(\0132/.WISE.FireEngineProto.CwfgmScenari" +
      "o.IdwExponent\022R\n\024globalAssetOperation\030\023 " +
      "\001(\01622.WISE.FireEngineProto.CwfgmScenario" +
      ".AssetOperationH\000\022!\n\024globalCollisionCoun" +
      "t\030\024 \001(\005H\006\210\001\001\032\210\005\n\024StopModellingOptions\022*\n" +
      "\014ResponseTime\030\001 \001(\0132\024.HSS.Times.WTimeSpa" +
      "n\022W\n\013FI90Percent\030\002 \001(\0132B.WISE.FireEngine" +
      "Proto.CwfgmScenario.StopModellingOptions" +
      ".Threshold\022W\n\013FI95Percent\030\003 \001(\0132B.WISE.F" +
      "ireEngineProto.CwfgmScenario.StopModelli" +
      "ngOptions.Threshold\022X\n\014FI100Percent\030\004 \001(" +
      "\0132B.WISE.FireEngineProto.CwfgmScenario.S" +
      "topModellingOptions.Threshold\022N\n\002RH\030\005 \001(" +
      "\0132B.WISE.FireEngineProto.CwfgmScenario.S" +
      "topModellingOptions.Threshold\022R\n\006Precip\030" +
      "\006 \001(\0132B.WISE.FireEngineProto.CwfgmScenar" +
      "io.StopModellingOptions.Threshold\022\032\n\004Are" +
      "a\030\007 \001(\0132\014.Math.Double\022\"\n\014BurnDistance\030\010 " +
      "\001(\0132\014.Math.Double\032T\n\tThreshold\022\037\n\tthresh" +
      "old\030\001 \001(\0132\014.Math.Double\022&\n\010duration\030\002 \001(" +
      "\0132\024.HSS.Times.WTimeSpan\032\264\001\n\nFmcOptions\022!" +
      "\n\013perOverride\030\001 \001(\0132\014.Math.Double\022 \n\nnod" +
      "ataElev\030\002 \001(\0132\014.Math.Double\022+\n\007terrain\030\003" +
      " \001(\0132\032.google.protobuf.BoolValue\0224\n\020accu" +
      "rateLocation\030\004 \001(\0132\032.google.protobuf.Boo" +
      "lValue\032\247\002\n\nFwiOptions\0224\n\020fwiSpacialInter" +
      "p\030\001 \001(\0132\032.google.protobuf.BoolValue\0229\n\025f" +
      "wiFromSpacialWeather\030\002 \001(\0132\032.google.prot" +
      "obuf.BoolValue\0228\n\024historyOnEffectedFwi\030\003" +
      " \001(\0132\032.google.protobuf.BoolValue\0227\n\023burn" +
      "ingConditionsOn\030\004 \001(\0132\032.google.protobuf." +
      "BoolValue\0225\n\021fwiTemporalInterp\030\005 \001(\0132\032.g" +
      "oogle.protobuf.BoolValue\032o\n\nFbpOptions\0221" +
      "\n\rterrainEffect\030\001 \001(\0132\032.google.protobuf." +
      "BoolValue\022.\n\nwindEffect\030\002 \001(\0132\032.google.p" +
      "rotobuf.BoolValue\032\217\n\n\nFgmOptions\022.\n\020maxA" +
      "ccelTimestep\030\001 \001(\0132\024.HSS.Times.WTimeSpan" +
      "\022\035\n\007distRes\030\002 \001(\0132\014.Math.Double\022\036\n\010perim" +
      "Res\030\003 \001(\0132\014.Math.Double\022\"\n\014minSpreadRos\030" +
      "\004 \001(\0132\014.Math.Double\0221\n\rstopAtGridEnd\030\005 \001" +
      "(\0132\032.google.protobuf.BoolValue\022-\n\tbreach" +
      "ing\030\006 \001(\0132\032.google.protobuf.BoolValue\022;\n" +
      "\027dynamicSpatialThreshold\030\007 \001(\0132\032.google." +
      "protobuf.BoolValue\022,\n\010spotting\030\010 \001(\0132\032.g" +
      "oogle.protobuf.BoolValue\0227\n\023purgeNonDisp" +
      "layable\030\t \001(\0132\032.google.protobuf.BoolValu" +
      "e\022\030\n\002dx\030\n \001(\0132\014.Math.Double\022\030\n\002dy\030\013 \001(\0132" +
      "\014.Math.Double\022 \n\002dt\030\014 \001(\0132\024.HSS.Times.WT" +
      "imeSpan\022;\n\027growthPercentileApplied\030\r \001(\013" +
      "2\032.google.protobuf.BoolValue\022&\n\020growthPe" +
      "rcentile\030\016 \001(\0132\014.Math.Double\0228\n\022initialV" +
      "ertexCount\030\017 \001(\0132\034.google.protobuf.UInt3" +
      "2Value\022\"\n\014ignitionSize\030\020 \001(\0132\014.Math.Doub" +
      "le\022(\n\016gridDecimation\030\021 \001(\0132\014.Math.Double" +
      "B\002\030\001\022\"\n\014perimSpacing\030\022 \001(\0132\014.Math.Double" +
      "\022;\n\027suppressTightConcaveAdd\030\023 \001(\0132\032.goog" +
      "le.protobuf.BoolValue\022/\n\013useCardinal\030\024 \001" +
      "(\0132\032.google.protobuf.BoolValue\0228\n\024indepe" +
      "ndentTimesteps\030\025 \001(\0132\032.google.protobuf.B" +
      "oolValue\022\031\n\003dWD\030\026 \001(\0132\014.Math.Double\022>\n\026n" +
      "onfuelsAsVectorBreaks\030\027 \001(\0132\032.google.pro" +
      "tobuf.BoolValueB\002\030\001\022>\n\026nonfuelsToVectorB" +
      "reaks\030\030 \001(\0132\032.google.protobuf.BoolValueB" +
      "\002\030\001\022\031\n\003oWD\030\031 \001(\0132\014.Math.Double\0225\n\021enable" +
      "FalseOrigin\030\032 \001(\0132\032.google.protobuf.Bool" +
      "Value\0226\n\022enableFalseScaling\030\033 \001(\0132\032.goog" +
      "le.protobuf.BoolValue\022\031\n\003oVD\030\034 \001(\0132\014.Mat" +
      "h.Double\022\031\n\003dVD\030\035 \001(\0132\014.Math.Double\032s\n\026S" +
      "cenarioFuelPercentile\022\017\n\007version\030\001 \001(\005\022\014" +
      "\n\004name\030\002 \001(\t\022\033\n\005crown\030\003 \001(\0132\014.Math.Doubl" +
      "e\022\035\n\007surface\030\004 \001(\0132\014.Math.Double\032\365\003\n\nCom" +
      "ponents\022@\n\tfireIndex\030\001 \003(\0132-.WISE.FireEn" +
      "gineProto.CwfgmScenario.Reference\022F\n\014wea" +
      "therIndex\030\002 \003(\01320.WISE.FireEngineProto.C" +
      "wfgmScenario.WeatherIndex\022B\n\013filterIndex" +
      "\030\003 \003(\0132-.WISE.FireEngineProto.CwfgmScena" +
      "rio.Reference\022B\n\013vectorIndex\030\004 \003(\0132-.WIS" +
      "E.FireEngineProto.CwfgmScenario.Referenc" +
      "e\022A\n\nassetIndex\030\005 \003(\0132-.WISE.FireEngineP" +
      "roto.CwfgmScenario.Reference\022G\n\nwindTarg" +
      "et\030\006 \001(\01323.WISE.FireEngineProto.CwfgmSce" +
      "nario.TargetReference\022I\n\014vectorTarget\030\007 " +
      "\001(\01323.WISE.FireEngineProto.CwfgmScenario" +
      ".TargetReference\032\372\001\n\tReference\022\016\n\004name\030\001" +
      " \001(\tH\000\022\017\n\005index\030\002 \001(\rH\000\022\023\n\006remove\030\003 \001(\010H" +
      "\002\210\001\001\022J\n\rfilterOptions\030\004 \001(\01321.WISE.FireE" +
      "ngineProto.CwfgmScenario.FilterOptionsH\001" +
      "\022H\n\014assetOptions\030\005 \001(\01320.WISE.FireEngine" +
      "Proto.CwfgmScenario.AssetOptionsH\001B\013\n\tre" +
      "ferenceB\t\n\007optionsB\t\n\007_remove\032\212\001\n\017Target" +
      "Reference\022\016\n\004name\030\001 \001(\tH\000\022\017\n\005index\030\002 \001(\r" +
      "H\000\022\023\n\006remove\030\003 \001(\010H\001\210\001\001\022\025\n\rgeometryIndex" +
      "\030\004 \001(\r\022\022\n\npointIndex\030\005 \001(\rB\013\n\treferenceB" +
      "\t\n\007_remove\032 \n\rFilterOptions\022\017\n\007subName\030\001" +
      " \003(\t\032\230\001\n\014AssetOptions\022G\n\toperation\030\001 \001(\016" +
      "22.WISE.FireEngineProto.CwfgmScenario.As" +
      "setOperationH\000\022\033\n\016collisionCount\030\002 \001(\005H\001" +
      "\210\001\001B\017\n\roperationNullB\021\n\017_collisionCount\032" +
      "\266\004\n\014WeatherIndex\022C\n\014stationIndex\030\001 \001(\0132-" +
      ".WISE.FireEngineProto.CwfgmScenario.Refe" +
      "rence\022B\n\013streamIndex\030\002 \001(\0132-.WISE.FireEn" +
      "gineProto.CwfgmScenario.Reference\022\026\n\tisP" +
      "rimary\030\003 \001(\010H\000\210\001\001\022\\\n\016weatherOptions\030\004 \001(" +
      "\0132D.WISE.FireEngineProto.CwfgmScenario.W" +
      "eatherIndex.WeatherIndexOptions\032\230\002\n\023Weat" +
      "herIndexOptions\022\017\n\007subName\030\001 \001(\t\022#\n\tstar" +
      "tTime\030\002 \001(\0132\020.HSS.Times.WTime\022!\n\007endTime" +
      "\030\003 \001(\0132\020.HSS.Times.WTime\022&\n\014ignitionTime" +
      "\030\004 \001(\0132\020.HSS.Times.WTime\022(\n\rwindDirectio" +
      "n\030\005 \001(\0132\014.Math.DoubleH\000\210\001\001\022-\n\022deltaWindD" +
      "irection\030\006 \001(\0132\014.Math.DoubleH\001\210\001\001B\020\n\016_wi" +
      "ndDirectionB\025\n\023_deltaWindDirectionB\014\n\n_i" +
      "sPrimary\032\335\001\n\013IdwExponent\022&\n\013temperature\030" +
      "\001 \001(\0132\014.Math.DoubleH\000\210\001\001\022$\n\twindSpeed\030\002 " +
      "\001(\0132\014.Math.DoubleH\001\210\001\001\022(\n\rprecipitation\030" +
      "\003 \001(\0132\014.Math.DoubleH\002\210\001\001\022\036\n\003fwi\030\004 \001(\0132\014." +
      "Math.DoubleH\003\210\001\001B\016\n\014_temperatureB\014\n\n_win" +
      "dSpeedB\020\n\016_precipitationB\006\n\004_fwi\"b\n\016Asse" +
      "tOperation\022\r\n\tNO_EFFECT\020\000\022\022\n\016STOP_IMMEDI" +
      "ATE\020\001\022\020\n\014STOP_AFTER_X\020\002\022\033\n\016STOP_AFTER_AL" +
      "L\020\377\377\377\377\377\377\377\377\377\001B\032\n\030globalAssetOperationNull" +
      "B\016\n\014_stopOptionsB\007\n\005_nameB\013\n\t_copyNameB\013" +
      "\n\t_commentsB\r\n\013_componentsB\027\n\025_globalCol" +
      "lisionCountB-\n\022ca.wise.fire.protoP\001\252\002\024WI" +
      "SE.FireEngineProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.hss.math.proto.Math.getDescriptor(),
          ca.hss.times.proto.WTimePackage.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          ca.wise.grid.proto.CwfgmFilter.getDescriptor(),
        });
    internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_FireEngineProto_CwfgmScenario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor,
        new java.lang.String[] { "Version", "StartTime", "EndTime", "DisplayInterval", "FbpOptions", "FgmOptions", "FmcOptions", "FwiOptions", "Percentiles", "StopOptions", "Name", "CopyName", "Comments", "TemporalConditions", "Components", "Idw", "GlobalAssetOperation", "GlobalCollisionCount", "GlobalAssetOperationNull", "StopOptions", "Name", "CopyName", "Comments", "Components", "GlobalCollisionCount", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_descriptor,
        new java.lang.String[] { "ResponseTime", "FI90Percent", "FI95Percent", "FI100Percent", "RH", "Precip", "Area", "BurnDistance", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_Threshold_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_Threshold_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_StopModellingOptions_Threshold_descriptor,
        new java.lang.String[] { "Threshold", "Duration", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_FmcOptions_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(1);
    internal_static_WISE_FireEngineProto_CwfgmScenario_FmcOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_FmcOptions_descriptor,
        new java.lang.String[] { "PerOverride", "NodataElev", "Terrain", "AccurateLocation", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_FwiOptions_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(2);
    internal_static_WISE_FireEngineProto_CwfgmScenario_FwiOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_FwiOptions_descriptor,
        new java.lang.String[] { "FwiSpacialInterp", "FwiFromSpacialWeather", "HistoryOnEffectedFwi", "BurningConditionsOn", "FwiTemporalInterp", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_FbpOptions_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(3);
    internal_static_WISE_FireEngineProto_CwfgmScenario_FbpOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_FbpOptions_descriptor,
        new java.lang.String[] { "TerrainEffect", "WindEffect", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_FgmOptions_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(4);
    internal_static_WISE_FireEngineProto_CwfgmScenario_FgmOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_FgmOptions_descriptor,
        new java.lang.String[] { "MaxAccelTimestep", "DistRes", "PerimRes", "MinSpreadRos", "StopAtGridEnd", "Breaching", "DynamicSpatialThreshold", "Spotting", "PurgeNonDisplayable", "Dx", "Dy", "Dt", "GrowthPercentileApplied", "GrowthPercentile", "InitialVertexCount", "IgnitionSize", "GridDecimation", "PerimSpacing", "SuppressTightConcaveAdd", "UseCardinal", "IndependentTimesteps", "DWD", "NonfuelsAsVectorBreaks", "NonfuelsToVectorBreaks", "OWD", "EnableFalseOrigin", "EnableFalseScaling", "OVD", "DVD", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_ScenarioFuelPercentile_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(5);
    internal_static_WISE_FireEngineProto_CwfgmScenario_ScenarioFuelPercentile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_ScenarioFuelPercentile_descriptor,
        new java.lang.String[] { "Version", "Name", "Crown", "Surface", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_Components_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(6);
    internal_static_WISE_FireEngineProto_CwfgmScenario_Components_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_Components_descriptor,
        new java.lang.String[] { "FireIndex", "WeatherIndex", "FilterIndex", "VectorIndex", "AssetIndex", "WindTarget", "VectorTarget", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_Reference_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(7);
    internal_static_WISE_FireEngineProto_CwfgmScenario_Reference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_Reference_descriptor,
        new java.lang.String[] { "Name", "Index", "Remove", "FilterOptions", "AssetOptions", "Reference", "Options", "Remove", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_TargetReference_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(8);
    internal_static_WISE_FireEngineProto_CwfgmScenario_TargetReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_TargetReference_descriptor,
        new java.lang.String[] { "Name", "Index", "Remove", "GeometryIndex", "PointIndex", "Reference", "Remove", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_FilterOptions_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(9);
    internal_static_WISE_FireEngineProto_CwfgmScenario_FilterOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_FilterOptions_descriptor,
        new java.lang.String[] { "SubName", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_AssetOptions_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(10);
    internal_static_WISE_FireEngineProto_CwfgmScenario_AssetOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_AssetOptions_descriptor,
        new java.lang.String[] { "Operation", "CollisionCount", "OperationNull", "CollisionCount", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(11);
    internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_descriptor,
        new java.lang.String[] { "StationIndex", "StreamIndex", "IsPrimary", "WeatherOptions", "IsPrimary", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_WeatherIndexOptions_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_WeatherIndexOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_WeatherIndex_WeatherIndexOptions_descriptor,
        new java.lang.String[] { "SubName", "StartTime", "EndTime", "IgnitionTime", "WindDirection", "DeltaWindDirection", "WindDirection", "DeltaWindDirection", });
    internal_static_WISE_FireEngineProto_CwfgmScenario_IdwExponent_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmScenario_descriptor.getNestedTypes().get(12);
    internal_static_WISE_FireEngineProto_CwfgmScenario_IdwExponent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmScenario_IdwExponent_descriptor,
        new java.lang.String[] { "Temperature", "WindSpeed", "Precipitation", "Fwi", "Temperature", "WindSpeed", "Precipitation", "Fwi", });
    ca.hss.math.proto.Math.getDescriptor();
    ca.hss.times.proto.WTimePackage.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    ca.wise.grid.proto.CwfgmFilter.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
