// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmScenario.proto

package ca.wise.fire.proto;

public interface CwfgmScenarioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.FireEngineProto.CwfgmScenario)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.HSS.Times.WTime startTime = 2;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 2;</code>
   * @return The startTime.
   */
  ca.hss.times.proto.WTime getStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 2;</code>
   */
  ca.hss.times.proto.WTimeOrBuilder getStartTimeOrBuilder();

  /**
   * <code>.HSS.Times.WTime endTime = 3;</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <code>.HSS.Times.WTime endTime = 3;</code>
   * @return The endTime.
   */
  ca.hss.times.proto.WTime getEndTime();
  /**
   * <code>.HSS.Times.WTime endTime = 3;</code>
   */
  ca.hss.times.proto.WTimeOrBuilder getEndTimeOrBuilder();

  /**
   * <code>.HSS.Times.WTimeSpan displayInterval = 4;</code>
   * @return Whether the displayInterval field is set.
   */
  boolean hasDisplayInterval();
  /**
   * <code>.HSS.Times.WTimeSpan displayInterval = 4;</code>
   * @return The displayInterval.
   */
  ca.hss.times.proto.WTimeSpan getDisplayInterval();
  /**
   * <code>.HSS.Times.WTimeSpan displayInterval = 4;</code>
   */
  ca.hss.times.proto.WTimeSpanOrBuilder getDisplayIntervalOrBuilder();

  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FbpOptions fbpOptions = 5;</code>
   * @return Whether the fbpOptions field is set.
   */
  boolean hasFbpOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FbpOptions fbpOptions = 5;</code>
   * @return The fbpOptions.
   */
  ca.wise.fire.proto.CwfgmScenario.FbpOptions getFbpOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FbpOptions fbpOptions = 5;</code>
   */
  ca.wise.fire.proto.CwfgmScenario.FbpOptionsOrBuilder getFbpOptionsOrBuilder();

  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FgmOptions fgmOptions = 6;</code>
   * @return Whether the fgmOptions field is set.
   */
  boolean hasFgmOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FgmOptions fgmOptions = 6;</code>
   * @return The fgmOptions.
   */
  ca.wise.fire.proto.CwfgmScenario.FgmOptions getFgmOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FgmOptions fgmOptions = 6;</code>
   */
  ca.wise.fire.proto.CwfgmScenario.FgmOptionsOrBuilder getFgmOptionsOrBuilder();

  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FmcOptions fmcOptions = 7;</code>
   * @return Whether the fmcOptions field is set.
   */
  boolean hasFmcOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FmcOptions fmcOptions = 7;</code>
   * @return The fmcOptions.
   */
  ca.wise.fire.proto.CwfgmScenario.FmcOptions getFmcOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FmcOptions fmcOptions = 7;</code>
   */
  ca.wise.fire.proto.CwfgmScenario.FmcOptionsOrBuilder getFmcOptionsOrBuilder();

  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FwiOptions fwiOptions = 8;</code>
   * @return Whether the fwiOptions field is set.
   */
  boolean hasFwiOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FwiOptions fwiOptions = 8;</code>
   * @return The fwiOptions.
   */
  ca.wise.fire.proto.CwfgmScenario.FwiOptions getFwiOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.FwiOptions fwiOptions = 8;</code>
   */
  ca.wise.fire.proto.CwfgmScenario.FwiOptionsOrBuilder getFwiOptionsOrBuilder();

  /**
   * <code>repeated .WISE.FireEngineProto.CwfgmScenario.ScenarioFuelPercentile percentiles = 11;</code>
   */
  java.util.List<ca.wise.fire.proto.CwfgmScenario.ScenarioFuelPercentile> 
      getPercentilesList();
  /**
   * <code>repeated .WISE.FireEngineProto.CwfgmScenario.ScenarioFuelPercentile percentiles = 11;</code>
   */
  ca.wise.fire.proto.CwfgmScenario.ScenarioFuelPercentile getPercentiles(int index);
  /**
   * <code>repeated .WISE.FireEngineProto.CwfgmScenario.ScenarioFuelPercentile percentiles = 11;</code>
   */
  int getPercentilesCount();
  /**
   * <code>repeated .WISE.FireEngineProto.CwfgmScenario.ScenarioFuelPercentile percentiles = 11;</code>
   */
  java.util.List<? extends ca.wise.fire.proto.CwfgmScenario.ScenarioFuelPercentileOrBuilder> 
      getPercentilesOrBuilderList();
  /**
   * <code>repeated .WISE.FireEngineProto.CwfgmScenario.ScenarioFuelPercentile percentiles = 11;</code>
   */
  ca.wise.fire.proto.CwfgmScenario.ScenarioFuelPercentileOrBuilder getPercentilesOrBuilder(
      int index);

  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.StopModellingOptions stopOptions = 12;</code>
   * @return Whether the stopOptions field is set.
   */
  boolean hasStopOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.StopModellingOptions stopOptions = 12;</code>
   * @return The stopOptions.
   */
  ca.wise.fire.proto.CwfgmScenario.StopModellingOptions getStopOptions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.StopModellingOptions stopOptions = 12;</code>
   */
  ca.wise.fire.proto.CwfgmScenario.StopModellingOptionsOrBuilder getStopOptionsOrBuilder();

  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 13;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 13;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 13;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string copyName = 14;</code>
   * @return Whether the copyName field is set.
   */
  boolean hasCopyName();
  /**
   * <code>string copyName = 14;</code>
   * @return The copyName.
   */
  java.lang.String getCopyName();
  /**
   * <code>string copyName = 14;</code>
   * @return The bytes for copyName.
   */
  com.google.protobuf.ByteString
      getCopyNameBytes();

  /**
   * <code>string comments = 15;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>string comments = 15;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 15;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>.WISE.GridProto.TemporalCondition temporalConditions = 16;</code>
   * @return Whether the temporalConditions field is set.
   */
  boolean hasTemporalConditions();
  /**
   * <code>.WISE.GridProto.TemporalCondition temporalConditions = 16;</code>
   * @return The temporalConditions.
   */
  ca.wise.grid.proto.TemporalCondition getTemporalConditions();
  /**
   * <code>.WISE.GridProto.TemporalCondition temporalConditions = 16;</code>
   */
  ca.wise.grid.proto.TemporalConditionOrBuilder getTemporalConditionsOrBuilder();

  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.Components components = 17;</code>
   * @return Whether the components field is set.
   */
  boolean hasComponents();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.Components components = 17;</code>
   * @return The components.
   */
  ca.wise.fire.proto.CwfgmScenario.Components getComponents();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.Components components = 17;</code>
   */
  ca.wise.fire.proto.CwfgmScenario.ComponentsOrBuilder getComponentsOrBuilder();

  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.IdwExponent idw = 18;</code>
   * @return Whether the idw field is set.
   */
  boolean hasIdw();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.IdwExponent idw = 18;</code>
   * @return The idw.
   */
  ca.wise.fire.proto.CwfgmScenario.IdwExponent getIdw();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.IdwExponent idw = 18;</code>
   */
  ca.wise.fire.proto.CwfgmScenario.IdwExponentOrBuilder getIdwOrBuilder();

  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.AssetOperation globalAssetOperation = 19;</code>
   * @return The enum numeric value on the wire for globalAssetOperation.
   */
  int getGlobalAssetOperationValue();
  /**
   * <code>.WISE.FireEngineProto.CwfgmScenario.AssetOperation globalAssetOperation = 19;</code>
   * @return The globalAssetOperation.
   */
  ca.wise.fire.proto.CwfgmScenario.AssetOperation getGlobalAssetOperation();

  /**
   * <pre>
   *the number of assets that can be collided into before a simulation will stop, if valid for the asset operation
   * </pre>
   *
   * <code>int32 globalCollisionCount = 20;</code>
   * @return Whether the globalCollisionCount field is set.
   */
  boolean hasGlobalCollisionCount();
  /**
   * <pre>
   *the number of assets that can be collided into before a simulation will stop, if valid for the asset operation
   * </pre>
   *
   * <code>int32 globalCollisionCount = 20;</code>
   * @return The globalCollisionCount.
   */
  int getGlobalCollisionCount();

  public ca.wise.fire.proto.CwfgmScenario.GlobalAssetOperationNullCase getGlobalAssetOperationNullCase();
}
