// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFire.proto

package ca.wise.fire.proto;

public final class CwfgmFire {
  private CwfgmFire() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmIgnition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmIgnition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionAttribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionAttribute_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017cwfgmFire.proto\022\024WISE.FireEngineProto\032" +
      "\013wtime.proto\032\017geography.proto\032\031google/pr" +
      "otobuf/any.proto\"\354\006\n\rCwfgmIgnition\022\017\n\007ve" +
      "rsion\030\001 \001(\005\022#\n\tstartTime\030\002 \001(\0132\020.HSS.Tim" +
      "es.WTime\022E\n\tignitions\030\003 \001(\01320.WISE.FireE" +
      "ngineProto.CwfgmIgnition.IgnitionListH\000\022" +
      "\022\n\010filename\030\004 \001(\tH\000\022\027\n\017file_attributes\030\005" +
      " \003(\t\022\021\n\004name\030\006 \001(\tH\001\210\001\001\022\025\n\010comments\030\007 \001(" +
      "\tH\002\210\001\001\022\022\n\005color\030\010 \001(\rH\003\210\001\001\022\026\n\tfillColor\030" +
      "\t \001(\rH\004\210\001\001\022\021\n\004size\030\n \001(\004H\005\210\001\001\022\023\n\006symbol\030" +
      "\013 \001(\004H\006\210\001\001\022\025\n\010imported\030\014 \001(\010H\007\210\001\001\032T\n\014Ign" +
      "itionList\022D\n\tignitions\030\001 \003(\01321.WISE.Fire" +
      "EngineProto.CwfgmIgnition.IgnitionPoint\032" +
      "\246\002\n\rIgnitionPoint\022Q\n\010polyType\030\001 \001(\0162?.WI" +
      "SE.FireEngineProto.CwfgmIgnition.Ignitio" +
      "nPoint.IgnitionShape\022#\n\007polygon\030\002 \001(\0132\022." +
      "Geography.GeoPoly\022I\n\nattributes\030\003 \003(\01325." +
      "WISE.FireEngineProto.CwfgmIgnition.Ignit" +
      "ionAttribute\"R\n\rIgnitionShape\022\013\n\007UNKNOWN" +
      "\020\000\022\t\n\005POINT\020\001\022\010\n\004LINE\020\002\022\017\n\013POLYGON_OUT\020\003" +
      "\022\016\n\nPOLYGON_IN\020\004\032F\n\021IgnitionAttribute\022\014\n" +
      "\004name\030\001 \001(\t\022#\n\005value\030\002 \001(\0132\024.google.prot" +
      "obuf.AnyB\006\n\004dataB\007\n\005_nameB\013\n\t_commentsB\010" +
      "\n\006_colorB\014\n\n_fillColorB\007\n\005_sizeB\t\n\007_symb" +
      "olB\013\n\t_importedB-\n\022ca.wise.fire.protoP\001\252" +
      "\002\024WISE.FireEngineProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.hss.times.proto.WTimePackage.getDescriptor(),
          ca.hss.math.proto.Geography.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_WISE_FireEngineProto_CwfgmIgnition_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_FireEngineProto_CwfgmIgnition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmIgnition_descriptor,
        new java.lang.String[] { "Version", "StartTime", "Ignitions", "Filename", "FileAttributes", "Name", "Comments", "Color", "FillColor", "Size", "Symbol", "Imported", "Data", "Name", "Comments", "Color", "FillColor", "Size", "Symbol", "Imported", });
    internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionList_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmIgnition_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionList_descriptor,
        new java.lang.String[] { "Ignitions", });
    internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionPoint_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmIgnition_descriptor.getNestedTypes().get(1);
    internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionPoint_descriptor,
        new java.lang.String[] { "PolyType", "Polygon", "Attributes", });
    internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionAttribute_descriptor =
      internal_static_WISE_FireEngineProto_CwfgmIgnition_descriptor.getNestedTypes().get(2);
    internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FireEngineProto_CwfgmIgnition_IgnitionAttribute_descriptor,
        new java.lang.String[] { "Name", "Value", });
    ca.hss.times.proto.WTimePackage.getDescriptor();
    ca.hss.math.proto.Geography.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
