// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmFire.proto

package ca.wise.fire.proto;

public interface CwfgmIgnitionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.FireEngineProto.CwfgmIgnition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.HSS.Times.WTime startTime = 2;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 2;</code>
   * @return The startTime.
   */
  ca.hss.times.proto.WTime getStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 2;</code>
   */
  ca.hss.times.proto.WTimeOrBuilder getStartTimeOrBuilder();

  /**
   * <code>.WISE.FireEngineProto.CwfgmIgnition.IgnitionList ignitions = 3;</code>
   * @return Whether the ignitions field is set.
   */
  boolean hasIgnitions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmIgnition.IgnitionList ignitions = 3;</code>
   * @return The ignitions.
   */
  ca.wise.fire.proto.CwfgmIgnition.IgnitionList getIgnitions();
  /**
   * <code>.WISE.FireEngineProto.CwfgmIgnition.IgnitionList ignitions = 3;</code>
   */
  ca.wise.fire.proto.CwfgmIgnition.IgnitionListOrBuilder getIgnitionsOrBuilder();

  /**
   * <code>string filename = 4;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 4;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   *Any attributes to record from the shapefile named in 'filename'.
   * </pre>
   *
   * <code>repeated string file_attributes = 5;</code>
   * @return A list containing the fileAttributes.
   */
  java.util.List<java.lang.String>
      getFileAttributesList();
  /**
   * <pre>
   *Any attributes to record from the shapefile named in 'filename'.
   * </pre>
   *
   * <code>repeated string file_attributes = 5;</code>
   * @return The count of fileAttributes.
   */
  int getFileAttributesCount();
  /**
   * <pre>
   *Any attributes to record from the shapefile named in 'filename'.
   * </pre>
   *
   * <code>repeated string file_attributes = 5;</code>
   * @param index The index of the element to return.
   * @return The fileAttributes at the given index.
   */
  java.lang.String getFileAttributes(int index);
  /**
   * <pre>
   *Any attributes to record from the shapefile named in 'filename'.
   * </pre>
   *
   * <code>repeated string file_attributes = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fileAttributes at the given index.
   */
  com.google.protobuf.ByteString
      getFileAttributesBytes(int index);

  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 7;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>string comments = 7;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 7;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>uint32 color = 8;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>uint32 color = 8;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <code>uint32 fillColor = 9;</code>
   * @return Whether the fillColor field is set.
   */
  boolean hasFillColor();
  /**
   * <code>uint32 fillColor = 9;</code>
   * @return The fillColor.
   */
  int getFillColor();

  /**
   * <code>uint64 size = 10;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <code>uint64 size = 10;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>uint64 symbol = 11;</code>
   * @return Whether the symbol field is set.
   */
  boolean hasSymbol();
  /**
   * <code>uint64 symbol = 11;</code>
   * @return The symbol.
   */
  long getSymbol();

  /**
   * <code>bool imported = 12;</code>
   * @return Whether the imported field is set.
   */
  boolean hasImported();
  /**
   * <code>bool imported = 12;</code>
   * @return The imported.
   */
  boolean getImported();

  public ca.wise.fire.proto.CwfgmIgnition.DataCase getDataCase();
}
